add subprojects

diff --git a/create_meson_cpp_skeleton_project b/create_meson_cpp_skeleton_project
--- a/create_meson_cpp_skeleton_project
+++ b/create_meson_cpp_skeleton_project
@@ -54,7 +54,7 @@ gtest_dep = gtest_proj.get_variable('gtest_main_dep')
 
 subdir('src')
 subdir('test')
-subdir('bin)
+subdir('bin')
 subdir('doc')
 //MY_CODE_STREAM
     sed -i "s/@ProjectSkeleton@/$PROJECT_NAME/g" "$CURRENT_FILE"
@@ -130,6 +130,58 @@ namespace @ProjectSkeleton@ {
     std::string hello();
     
 }
+//MY_CODE_STREAM
+    sed -i "s/@ProjectSkeleton@/$PROJECT_NAME/g" "$CURRENT_FILE"
+else 
+    echo "File $CURRENT_FILE already exists, aborted! (you can use -f to force overwrite)" 
+    exit 1
+fi
+
+#----------------
+
+CURRENT_FILE="$PROJECT_ROOT_DIRECTORY/src/$PROJECT_NAME/hello.cpp"
+
+if [ "$FORCE" -eq 1 ] || [ ! -f "$CURRENT_FILE" ]; then
+    echo "Creates file      $CURRENT_FILE" 
+    more > "$CURRENT_FILE" <<'//MY_CODE_STREAM' 
+#include "hello.hpp"
+
+namespace @ProjectSkeleton@ {
+
+  std::string hello() {
+    return "hello @ProjectSkeleton@";
+  };
+    
+}
+//MY_CODE_STREAM
+    sed -i "s/@ProjectSkeleton@/$PROJECT_NAME/g" "$CURRENT_FILE"
+else 
+    echo "File $CURRENT_FILE already exists, aborted! (you can use -f to force overwrite)" 
+    exit 1
+fi
+
+#================================================================
+
+echo "Creates directory $PROJECT_ROOT_DIRECTORY/subprojects" 
+mkdir -p "$PROJECT_ROOT_DIRECTORY/subprojects"
+
+#----------------
+
+CURRENT_FILE="$PROJECT_ROOT_DIRECTORY/subprojects/gtest.wrap"
+
+if [ "$FORCE" -eq 1 ] || [ ! -f "$CURRENT_FILE" ]; then
+    echo "Creates file      $CURRENT_FILE" 
+    more > "$CURRENT_FILE" <<'//MY_CODE_STREAM' 
+[wrap-file]
+directory = googletest-release-1.8.0
+
+source_url = https://github.com/google/googletest/archive/release-1.8.0.zip
+source_filename = gtest-1.8.0.zip
+source_hash = f3ed3b58511efd272eb074a3a6d6fb79d7c2e6a0e374323d1e6bcbcc1ef141bf
+
+patch_url = https://wrapdb.mesonbuild.com/v1/projects/gtest/1.8.0/5/get_zip
+patch_filename = gtest-1.8.0-5-wrap.zip
+patch_hash = 7eeaede4aa2610a403313b74e04baf91ccfbaef03203d8f56312e22df1834ec5
 //MY_CODE_STREAM
     sed -i "s/@ProjectSkeleton@/$PROJECT_NAME/g" "$CURRENT_FILE"
 else 
